/* Generated By:JavaCC: Do not edit this line. MooplParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MooplParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROC = 8;
  /** RegularExpression Id. */
  int FUN = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 11;
  /** RegularExpression Id. */
  int ID = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"proc\"",
    "\"fun\"",
    "\"class\"",
    "<INTEGER_LITERAL>",
    "<ID>",
  };

}
